package assets

// FontOptionsMap is a static map that associates a base font name with a list of options and file paths
var baseDirNotoSans = "assets/fonts/Noto-Sans/static/"
var FontOptionsMap = map[string]map[string]string{
	"NotoSans": {
		"Black":            baseDirNotoSans + "NotoSans-Black.ttf",
		"BlackItalic":      baseDirNotoSans + "NotoSans-BlackItalic.ttf",
		"Bold":             baseDirNotoSans + "NotoSans-Bold.ttf",
		"BoldItalic":       baseDirNotoSans + "NotoSans-BoldItalic.ttf",
		"ExtraBold":        baseDirNotoSans + "NotoSans-ExtraBold.ttf",
		"ExtraBoldItalic":  baseDirNotoSans + "NotoSans-ExtraBoldItalic.ttf",
		"ExtraLight":       baseDirNotoSans + "NotoSans-ExtraLight.ttf",
		"ExtraLightItalic": baseDirNotoSans + "NotoSans-ExtraLightItalic.ttf",
		"Italic":           baseDirNotoSans + "NotoSans-Italic.ttf",
		"Light":            baseDirNotoSans + "NotoSans-Light.ttf",
		"LightItalic":      baseDirNotoSans + "NotoSans-LightItalic.ttf",
		"Medium":           baseDirNotoSans + "NotoSans-Medium.ttf",
		"MediumItalic":     baseDirNotoSans + "NotoSans-MediumItalic.ttf",
		"Regular":          baseDirNotoSans + "NotoSans-Regular.ttf",
		"SemiBold":         baseDirNotoSans + "NotoSans-SemiBold.ttf",
		"SemiBoldItalic":   baseDirNotoSans + "NotoSans-SemiBoldItalic.ttf",
		"Thin":             baseDirNotoSans + "NotoSans-Thin.ttf",
		"ThinItalic":       baseDirNotoSans + "NotoSans-ThinItalic.ttf",
	},
	"NotoSans_Condensed": {
		"Black":            baseDirNotoSans + "NotoSans_Condensed-Black.ttf",
		"BlackItalic":      baseDirNotoSans + "NotoSans_Condensed-BlackItalic.ttf",
		"Bold":             baseDirNotoSans + "NotoSans_Condensed-Bold.ttf",
		"BoldItalic":       baseDirNotoSans + "NotoSans_Condensed-BoldItalic.ttf",
		"ExtraBold":        baseDirNotoSans + "NotoSans_Condensed-ExtraBold.ttf",
		"ExtraBoldItalic":  baseDirNotoSans + "NotoSans_Condensed-ExtraBoldItalic.ttf",
		"ExtraLight":       baseDirNotoSans + "NotoSans_Condensed-ExtraLight.ttf",
		"ExtraLightItalic": baseDirNotoSans + "NotoSans_Condensed-ExtraLightItalic.ttf",
		"Italic":           baseDirNotoSans + "NotoSans_Condensed-Italic.ttf",
		"Light":            baseDirNotoSans + "NotoSans_Condensed-Light.ttf",
		"LightItalic":      baseDirNotoSans + "NotoSans_Condensed-LightItalic.ttf",
		"Medium":           baseDirNotoSans + "NotoSans_Condensed-Medium.ttf",
		"MediumItalic":     baseDirNotoSans + "NotoSans_Condensed-MediumItalic.ttf",
		"Regular":          baseDirNotoSans + "NotoSans_Condensed-Regular.ttf",
		"SemiBold":         baseDirNotoSans + "NotoSans_Condensed-SemiBold.ttf",
		"SemiBoldItalic":   baseDirNotoSans + "NotoSans_Condensed-SemiBoldItalic.ttf",
		"Thin":             baseDirNotoSans + "NotoSans_Condensed-Thin.ttf",
		"ThinItalic":       baseDirNotoSans + "NotoSans_Condensed-ThinItalic.ttf",
	},
	"NotoSans_ExtraCondensed": {
		"Black":            baseDirNotoSans + "NotoSans_ExtraCondensed-Black.ttf",
		"BlackItalic":      baseDirNotoSans + "NotoSans_ExtraCondensed-BlackItalic.ttf",
		"Bold":             baseDirNotoSans + "NotoSans_ExtraCondensed-Bold.ttf",
		"BoldItalic":       baseDirNotoSans + "NotoSans_ExtraCondensed-BoldItalic.ttf",
		"ExtraBold":        baseDirNotoSans + "NotoSans_ExtraCondensed-ExtraBold.ttf",
		"ExtraBoldItalic":  baseDirNotoSans + "NotoSans_ExtraCondensed-ExtraBoldItalic.ttf",
		"ExtraLight":       baseDirNotoSans + "NotoSans_ExtraCondensed-ExtraLight.ttf",
		"ExtraLightItalic": baseDirNotoSans + "NotoSans_ExtraCondensed-ExtraLightItalic.ttf",
		"Italic":           baseDirNotoSans + "NotoSans_ExtraCondensed-Italic.ttf",
		"Light":            baseDirNotoSans + "NotoSans_ExtraCondensed-Light.ttf",
		"LightItalic":      baseDirNotoSans + "NotoSans_ExtraCondensed-LightItalic.ttf",
		"Medium":           baseDirNotoSans + "NotoSans_ExtraCondensed-Medium.ttf",
		"MediumItalic":     baseDirNotoSans + "NotoSans_ExtraCondensed-MediumItalic.ttf",
		"Regular":          baseDirNotoSans + "NotoSans_ExtraCondensed-Regular.ttf",
		"SemiBold":         baseDirNotoSans + "NotoSans_ExtraCondensed-SemiBold.ttf",
		"SemiBoldItalic":   baseDirNotoSans + "NotoSans_ExtraCondensed-SemiBoldItalic.ttf",
		"Thin":             baseDirNotoSans + "NotoSans_ExtraCondensed-Thin.ttf",
		"ThinItalic":       baseDirNotoSans + "NotoSans_ExtraCondensed-ThinItalic.ttf",
	},
}
